title: FE2CM Docs
description: Documentation for FE2CM and its Timelines system.
theme: just-the-docs

color_scheme: dark
url: https://thelivingpepsi.github.io/fe2cm-docs/

favicon_ico: "/assets/images/favicon.ico"

aux_links:
  Site Repository: https://github.com/TheLivingPepsi/fe2cm-docs
