title: FE2CM Documentation
description: Custom documentation for FE2CM and Timelines
theme: just-the-docs

url: https://thelivingpepsi.github.io/fe2cm-docs/

aux_links:
  Template Repository: https://github.com/TheLivingPepsi/fe2cm-docs/
